run:
  timeout: 5m
  go: 1.23

linters:
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - gofumpt
    - goimports
    - govet
    - errcheck
    - gosec

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    # Exclude `lll` issues for long lines with `go:generate`.
    - linters:
        - lll
      source: "^//go:generate "

linters-settings:
  gofumpt:
    extra-rules: true
    module-path: github.com/netapp/trident

  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    # It's a comma-separated list of prefixes.
    local-prefixes: github.com/netapp/trident

  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    line-length: 120
    # Tab width in spaces.
    tab-width: 4

  gosec:
    excludes:
      # Exclude TLS client side erorrs for now, until Trident fully supports TLS1.3
      - G402 # Look for bad TLS connection settings
      - G115

  govet:
    disable:
      - printf
