{{- if include "shouldInstallRancherRoles" . | eq "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trident-operator-rancher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trident-operator-rancher
subjects:
  - kind: ServiceAccount
    name: trident-operator
    namespace: {{ .Release.Namespace }}
{{- end }}
