{{- if or .Values.anfConfigurator.enabled .Values.ontapConfigurator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: trident-operator
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: operator.trident.netapp.io
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8002
---
apiVersion: v1
kind: Pod
metadata:
  name: trident-post-install-upgrade-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
  restartPolicy: Never
  {{- if .Values.affinity }}
  affinity:
{{ toYaml .Values.affinity | nindent 4 }}
  {{- end }}
  {{- if .Values.nodeSelector }}
  nodeSelector:
{{ toYaml .Values.nodeSelector | nindent 4 }}
  {{- end }}
  {{- if .Values.tolerations }}
  tolerations:
{{ toYaml .Values.tolerations | nindent 4 }}
  {{- end }}
  initContainers:
    - name: init-container-1
      image: {{ include "trident.image" $ }}
      command:
        - tridentctl
        - --debug
        - -s
        - 127.0.0.1:8000
        - check
        - operator
        - --timeout
        - "7200" # Keeping it 12 mins as AKS extension script has an upper limit of 15 mins.
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  containers:
    - name: trident-post-hook
      image: {{ include "trident.image" $ }}
      command:
        - tridentctl
        - --debug
        - -s
        - 127.0.0.1:8000
        - check
        - operator
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- end }}
