{{- if .Values.anfConfigurator.enabled }}
apiVersion: trident.netapp.io/v1
kind: TridentConfigurator
metadata:
  name: netapp-anf-backend-configurator
spec:
  storageDriverName: azure-netapp-files
  {{- if eq .Values.cloudProvider "" }}
  tenantID: {{ .Values.anfConfigurator.tenantID }}
  clientCredentials: {{ .Values.anfConfigurator.clientCredentials }}
  {{- end }}
  {{- if or (eq .Values.cloudProvider "") (and (eq .Values.cloudProvider "Azure") (ne .Values.cloudIdentity "")) }}
  subscriptionID: {{ .Values.anfConfigurator.subscriptionID }}
  location: {{ .Values.anfConfigurator.location }}
  {{- end }}
  virtualNetwork: {{ .Values.anfConfigurator.virtualNetwork }}
  subnet: {{ .Values.anfConfigurator.subnet }}
  capacityPools:
    {{- range .Values.anfConfigurator.capacityPools }}
    - {{ . }}
    {{- end }}
  netappAccounts:
    {{- range .Values.anfConfigurator.netappAccounts }}
    - {{ . }}
    {{- end }}
  resourceGroups:
    {{- range .Values.anfConfigurator.resourceGroups }}
    - {{ . }}
    {{- end }}
  customerEncryptionKeys:
    {{- range $key, $value := .Values.anfConfigurator.customerEncryptionKeys }}
      {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}

---

{{- if .Values.ontapConfigurator.enabled }}
{{- $includeCR := false }}
{{- range .Values.ontapConfigurator.svms }}
  {{- if or (has "nfs" .protocols) (has "smb" .protocols) }}
    {{- $includeCR = true }}
  {{- end }}
{{- end }}

{{- if $includeCR }}
apiVersion: trident.netapp.io/v1
kind: TridentConfigurator
metadata:
  name: netapp-nas-backend-configurator
spec:
  storageDriverName: ontap-nas
  svms:
  {{- range .Values.ontapConfigurator.svms }}
    {{- if or (has "nfs" .protocols) (has "smb" .protocols) }}
    - fsxnID: {{ .fsxnID | quote }}
      protocols:
      {{- $filteredProtocols := list }}
      {{- range .protocols }}
        {{- if or (eq . "nfs") (eq . "smb") }}
          {{- $filteredProtocols = append $filteredProtocols . }}
        {{- end }}
      {{- end }}
      {{- range $filteredProtocols }}
        - {{ . | quote }}
      {{- end }}
      svmName: {{ .svmName | quote }}
      authType: {{ .authType | default "awsarn" | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}


---

{{- if .Values.ontapConfigurator.enabled }}
{{- $includeCR := false }}
{{- range .Values.ontapConfigurator.svms }}
  {{- if or (has "iscsi" .protocols) (has "nvme" .protocols) }}
    {{- $includeCR = true }}
  {{- end }}
{{- end }}

{{- if $includeCR }}
apiVersion: trident.netapp.io/v1
kind: TridentConfigurator
metadata:
  name: netapp-san-backend-configurator
spec:
  storageDriverName: ontap-san
  svms:
  {{- range .Values.ontapConfigurator.svms }}
    {{- if or (has "iscsi" .protocols) (has "nvme" .protocols) }}
    - fsxnID: {{ .fsxnID | quote }}
      protocols:
      {{- $filteredProtocols := list }}
      {{- range .protocols }}
        {{- if or (eq . "iscsi") (eq . "nvme") }}
          {{- $filteredProtocols = append $filteredProtocols . }}
        {{- end }}
      {{- end }}
      {{- range $filteredProtocols }}
        - {{ . | quote }}
      {{- end }}
      svmName: {{ .svmName | quote }}
      authType: {{ .authType | default "awsarn" | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
