apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-failover
  labels:
    app: trident-failover
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trident-failover
  template:
    metadata:
      labels:
        app: trident-failover
    spec:
      containers:
      - name: trident-failover
        image: busybox:1.36
        command: ["sleep", "infinity"]
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - trident-failover
              topologyKey: kubernetes.io/hostname
